replicaCount: 2

image:
  repository: 383313559988.dkr.ecr.us-east-1.amazonaws.com/payment-service
  pullPolicy: IfNotPresent
  tag: "ed59eae9d0eb02208480091284f79563e14028f0"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi